# [gluoncv.data.batchify¶](https://gluon-cv.mxnet.io/api/data.batchify.html)

## Stack

Stack the input data samples to construct the batch. The N input samples must have the same shape/length and will be stacked to construct a batch：

In [1]:
from gluoncv.data import batchify

In [2]:
# Stack multiple lists
a = [1, 2, 3, 4]
b = [4, 5, 6, 8]
c = [8, 9, 1, 2]
batchify.Stack()([a, b, c])


[[1. 2. 3. 4.]
 [4. 5. 6. 8.]
 [8. 9. 1. 2.]]
<NDArray 3x4 @cpu_shared(0)>

In [4]:
import numpy as np
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
b = np.array([[5, 6, 7, 8], [1, 2, 3, 4]])
batchify.Stack()([a, b])


[[[1. 2. 3. 4.]
  [5. 6. 7. 8.]]

 [[5. 6. 7. 8.]
  [1. 2. 3. 4.]]]
<NDArray 2x2x4 @cpu_shared(0)>

In [5]:
# Stack multiple NDArrays
import mxnet as mx
a = mx.nd.array([[1, 2, 3, 4], [5, 6, 7, 8]])
b = mx.nd.array([[5, 6, 7, 8], [1, 2, 3, 4]])
batchify.Stack()([a, b])


[[[1. 2. 3. 4.]
  [5. 6. 7. 8.]]

 [[5. 6. 7. 8.]
  [1. 2. 3. 4.]]]
<NDArray 2x2x4 @cpu_shared(0)>

## Pad

`Pad(axis=0, pad_val=0, ret_length=False)`

Pad the input ndarrays along the specific padding axis and stack them to get the output. Input of the function will be N samples. Each sample should contain a single element that can be 1) numpy.ndarray, 2) mxnet.nd.NDArray, 3) list of numbers. You can set the axis and pad_val to determine the padding axis and value. The arrays will be padded to the largest dimension at axis and then stacked to form the final output. In addition, the function will output the original dimensions at the axis if ret_length is turned on. :param axis: The axis to pad the arrays.

In [6]:
# Inputs are multiple lists
a = [1, 2, 3, 4]
b = [4, 5, 6]
c = [8, 2]
batchify.Pad()([a, b, c])


[[1 2 3 4]
 [4 5 6 0]
 [8 2 0 0]]
<NDArray 3x4 @cpu_shared(0)>

In [7]:
# Also output the lengths
a = [1, 2, 3, 4]
b = [4, 5, 6]
c = [8, 2]
batchify.Pad(ret_length=True)([a, b, c])

(
 [[1 2 3 4]
  [4 5 6 0]
  [8 2 0 0]]
 <NDArray 3x4 @cpu_shared(0)>, 
 [4 3 2]
 <NDArray 3 @cpu_shared(0)>)

In [8]:
# Inputs are multiple ndarrays
import numpy as np
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
b = np.array([[5, 8], [1, 2]])
batchify.Pad(axis=1, pad_val=-1)([a, b])


[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 5  8 -1 -1]
  [ 1  2 -1 -1]]]
<NDArray 2x2x4 @cpu_shared(0)>

In [9]:
# Inputs are multiple NDArrays
import mxnet as mx
a = mx.nd.array([[1, 2, 3, 4], [5, 6, 7, 8]])
b = mx.nd.array([[5, 8], [1, 2]])
batchify.Pad(axis=1, pad_val=-1)([a, b])


[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]]

 [[ 5.  8. -1. -1.]
  [ 1.  2. -1. -1.]]]
<NDArray 2x2x4 @cpu_shared(0)>

## Append(expand=True, batch_axis=0)

Loosely return list of the input data samples. There is no constraint of shape for any of the input samples, however, you will only be able to apply single batch operations since the output have different shapes.

In [10]:
a = [1, 2, 3, 4]
b = [4, 5, 6]
c = [8, 2]
batchify.Append()([a, b, c])

[
 [[1. 2. 3. 4.]]
 <NDArray 1x4 @cpu(0)>, 
 [[4. 5. 6.]]
 <NDArray 1x3 @cpu(0)>, 
 [[8. 2.]]
 <NDArray 1x2 @cpu(0)>]

## Tuple(fn, *args)

Wrap multiple batchify functions to form a function apply each input function on each input fields respectively. Each data sample should be a list or tuple containing multiple attributes. The i`th batchify function stored in `Tuple will be applied on the i`th attribute. For example, each data sample is (nd_data, label). You can wrap two batchify functions using `Wrap(DataBatchify, LabelBatchify) to batchify nd_data and label correspondingly. :param fn: The batchify functions to wrap. :type fn: list or tuple or callable :param *args: The additional batchify functions to wrap. :type *args: tuple of callable

In [11]:
a = ([1, 2, 3, 4], 0)
b = ([5, 7], 1)
c = ([1, 2, 3, 4, 5, 6, 7], 0)
batchify.Tuple(batchify.Pad(), batchify.Stack())([a, b])

(
 [[1 2 3 4]
  [5 7 0 0]]
 <NDArray 2x4 @cpu_shared(0)>, 
 [0. 1.]
 <NDArray 2 @cpu_shared(0)>)

In [12]:
# Input can also be a list
batchify.Tuple([batchify.Pad(), batchify.Stack()])([list(a), list(b)])

(
 [[1 2 3 4]
  [5 7 0 0]]
 <NDArray 2x4 @cpu_shared(0)>, 
 [0. 1.]
 <NDArray 2 @cpu_shared(0)>)

In [13]:
# Another example
a = ([1, 2, 3, 4], [5, 6], 1)
b = ([1, 2], [3, 4, 5, 6], 0)
c = ([1], [2, 3, 4, 5, 6], 0)
batchify.Tuple(batchify.Pad(), batchify.Pad(), batchify.Stack())([a, b, c])

(
 [[1 2 3 4]
  [1 2 0 0]
  [1 0 0 0]]
 <NDArray 3x4 @cpu_shared(0)>, 
 [[5 6 0 0 0]
  [3 4 5 6 0]
  [2 3 4 5 6]]
 <NDArray 3x5 @cpu_shared(0)>, 
 [1. 0. 0.]
 <NDArray 3 @cpu_shared(0)>)